### ISSUE TITLE
Doesn't handle \` escapes correctly

### ISSUE THREAD

**Issue by UltCombo** [dmnd/dedent#2]
Expected:
```js
dd`\`` === '`'
```

Actual:

```js
dd`\`` === '\\`'
```

**Comment by dmnd** [comment]
Thanks for reporting, that's definitely buggy.

**Comment by UltCombo** [comment]
Nice! Thanks. :smile:

**Comment by G-Rath** [comment]
Ironically #26 was opened reporting the fixed behaviour as a bug 😂

On a related note, given that the OP behaviour was a bug, I think it's a bug that `\{` & `\$` are escaped too?

Currently I'm having issues with this:

```
dedent`
const identifier = '@typescript-eslint/camelcase';

module.exports = {
  rules: {
    'no-unused-expression': 'error',
    [\`$\{identifier}\`]: 'error'
  }
}
````

This outputs:

```
const identifier = '@typescript-eslint/camelcase';

module.exports = {
  rules: {
    'no-unused-expression': 'error',
    [`$\{identifier}`]: 'error'
  }
}
```

**Comment by G-Rath** [comment]
@dmnd I'd love to get this fixed - if you're still interested in maintaining this package, I'll open a PR; otherwise I'd be happy to take over or share maintaining this package :)

I also realised I didn't post my workaround, which was to use `.replace(/\\\{/u, '{')` after the `dedent` call.

**Comment by G-Rath** [comment]
@JoshuaKGoldberg since you've now maintaining this we should get this on the radar - I'll try to reload the context into my brain and confirm if its still a thing and if so what the next steps are, but you might have the bandwidth to get to that before I do 🙂

**Comment by JoshuaKGoldberg** [comment]
🙌 super, yes! If you can file a new issue with a new repro I can triage it. And if you have time to send a PR for me to review that'd be great; otherwise I should be able to send one soon.

**Comment by G-Rath** [comment]
@JoshuaKGoldberg have opened #45
