### ISSUE TITLE
Feature request: support `join` option

### ISSUE THREAD

**Issue by scottrippey** [dmnd/dedent#21]
I would like a "join" option, so that multi-line strings could be both dedented and joined into a single line.  
Example:
```
example = dedent(' ', `
  This is a
  multiline string
  that is joined with spaces
  instead of newlines.
`); // "This is a multiline string that is joined with spaces instead of newlines."
```

A little backstory, I actually have my own `dedent` function implemented in several projects, and use it constantly!  I found this repo when thinking about publishing my `dedent`.  I'm glad to see it already exists!  
This 'join' feature is something I use quite often, too, so I'm hoping its something I could add to this project.
Let's discuss?

**Comment by JoshuaKGoldberg** [comment]
Interesting idea! Seems a little out of scope for the project at this point though (#36). Maybe a good new package to publish on its own?
