### ISSUE TITLE
ES Module

### ISSUE THREAD

**Issue by bennypowers** [dmnd/dedent#25]
Please publish as an ES Module.

If users need CJS, it could be compiled from the standard javascript.

**Comment by Haroenv** [comment]
should be possible by making a custom babel config with `modules: false` in the transform; and then outputting to a separate file in `dist`. Do you want to contribute?

**Comment by fineline** [comment]
Or ... you could switch the flow type annotations in your source code to use comment style, so your source file itself is a valid ES6 module. Then the following import would work in-browser:

```js
import dedent from "./node_modules/dedent/dedent.js
```

Happy to do PR for that if considered acceptable.
