### ISSUE TITLE
Handle escaped backticks is wrong when dedent used as function

### ISSUE THREAD

**Issue by sirian** [dmnd/dedent#26]
```
dedent("\\`") === "`"
```

Bug in this line https://github.com/dmnd/dedent/blob/master/dedent.js#L17

**Comment by JoshuaKGoldberg** [comment]
👋 @sirian! Recognizing this is a few years old - if it's still something you have both time and interest for, I posted a proposal for adding an option in #63. Seeking input if you have time!
