### ISSUE TITLE
Allow first line to be blank

### ISSUE THREAD

**Issue by moll** [dmnd/dedent#3]
E.g.:
```js
      console.log(dedent`
        if foo
          br
          hr
      `)
```

Cheers

**Comment by dmnd** [comment]
What output are you expecting here?

**Comment by moll** [comment]
Hey,

> What output are you expecting here?

```
if foo
  br
  hr
```

**Comment by dmnd** [comment]
I'm pretty sure that works already. Isn't it the same as [this test case](https://github.com/dmnd/dedent/blob/master/__tests__/dedent-tests.js#L32)?

Going to close the issue, but we can reopen if there really is a bug here.

**Comment by moll** [comment]
Maybe you're right or maybe I was actually using multiple blank lines, but prematurely generalized that bug report to "first blank line". Thanks anyways. I'll come back should I notice it not working.
