### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by TwitchBronBron** [dmnd/dedent#35]
There are several pull requests and unanswered issues. Is this project dead?

**Comment by maurer2** [comment]
Hello, probably, but you can use https://github.com/tamino-martinius/node-ts-dedent instead.

Cheers

**Comment by JoshuaKGoldberg** [comment]
👋! It somewhat was, but is no longer. dmnd just gave me access to manage the repo - I'll be taking over maintenance. Will post a pinned issue soon. Cheers!
