### ISSUE TITLE
1.0.1 type change

### ISSUE THREAD

**Issue by jlarmstrongiv** [dmnd/dedent#43]
> Argument of type 'string' is not assignable to parameter of type 'TemplateStringsArray'.

Means this code in the readme (and the code I wrote 😂) is no longer valid:

```ts
const third = dedent(`
    Wait! I lied. Dedent can also be used as a function.
`);
```

The workaround is to use ES6 string tags:

```ts
const first = dedent`A string`
```

**Comment by JoshuaKGoldberg** [comment]
This should be fixed in [`dedent@1.0.2`](https://www.npmjs.com/package/dedent/v/1.0.2). Thanks for reporting @jlarmstrongiv!
