### ISSUE TITLE
Bug(?) JSON.serialize(..., null, 2) throws off indentation

### ISSUE THREAD

**Issue by magicmark** [dmnd/dedent#78]
not sure if this is a bug or somehow expected behaviour that i don't understand yet, but here's a lil repro:

```
$ cat test.js 
const dedent = require('dedent');

console.log(
    dedent`
        Foo
        ${JSON.stringify({ a: 'b' }, null, 2)}
        Bar
    `,
);

$ node src/test.js 
Foo
      {
"a": "b"
}
      Bar
```

Observations:
- the `Bar` line is not at the same level of indentation as Foo.
- the serialized json string has odd indentation, but i sort of understand why this happens, and might be outside the scope of this library to fix....but would be super nice if it did :P
- same thing happens with util.inspect

thanks!

**Comment by magicmark** [comment]
fwiw this hack does what I want:

```
console.log(
    dedent`
        Foo
        ${JSON.stringify(JSON.stringify({ a: 'b' }, null, 2))
            .replace(/\\"/g, '"')
            .replace(/^\"/, '')
            .replace(/\"$/, '')}
        Bar
        Baz
        Qux
    `,
);
```

outputs:

```
$ node test.js
Foo
{
  "a": "b"
}
Bar
Baz
Qux
```

**Comment by JoshuaKGoldberg** [comment]
Interesting! The way template literal string work is by passing an array of strings and then the interpolated values to go in-between them:

```js
const logArgs = (...args) => console.log(args);

logArgs`
  Foo
  ${JSON.stringify({ a: "b" }, null, 2)}
  Bar
`;
```

```plaintext
[
  [ '\n  Foo\n  ', '\n  Bar\n' ],
  '{\n  "a": "b"\n}'
]
```

I think this is a dup of #12, generally asking to dedent nested strings? Closing as such but please post back if I'm wrong. Thanks!
