### ISSUE TITLE
error with npm install on firebase project 

### ISSUE THREAD

**Issue by devnoaman** [dmnd/dedent#79]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://repo.huaweicloud.com/repository/npm/dedent/-/dedent-1.5.1.tgz
npm ERR! 404 
npm ERR! 404  'dedent@https://repo.huaweicloud.com/repository/npm/dedent/-/dedent-1.5.1.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Haroenv** [comment]
This seems to be related to the Huawei cloud registry you're using. I don't see that issue on npm or yarn
