### ISSUE TITLE
🐛 Bug: Doesn't do dedent if first character is a space character

### ISSUE THREAD

**Issue by AlexMost** [dmnd/dedent#81]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/dmnd/dedent/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

```js
const d = require('dedent')
const result = d(' first line\n   second line'); // has space character at the beginning

// result is  'first line\nsecond line'
```

Expecting first line and second lines to be dedented

### Actual

```js
const d = require('dedent')
const result = d(' first line\n   second line'); // has space character at the beginning

// result is  'first line\n   second line'
```

Actual behavior is that the first space is stripped and the second line is not dedented

### Additional Info

All code was executed and tested on the library version `1.5.1`

node.js - v16.15.1

**Comment by Haroenv** [comment]
This is expected, as the goal of decent is to remove leading space, but only the "minimal amount", so that you can write for example:

```js
dedent`
  something
   something else
`
```

and have that output

```
something
 something else
```

If you want to strip all leading space, I suggest you map over each line and call `trimStart` on each line

**Comment by AlexMost** [comment]
Thanks for the clarification, probably going to implement the simplified version of the dedent.
