### ISSUE TITLE
🐛 Bug: Upgrading Node to verison 18 broke builds

### ISSUE THREAD

**Issue by dontforgit** [dmnd/dedent#92]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/dmnd/dedent/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

A major node version dependency should not be upgraded in a bug fix. 

### Actual

[NPM is showing](https://www.npmjs.com/package/dedent?activeTab=versions) the latest version is `1.5.2`, which requires Node `18`. This is breaking our application since Jest `29.5.0` has this somewhere in the dependency tree only supporting Node `16`. 

### Additional Info

It looks like that tag was removed from GitHub. A new tag that reverts functionality back to `1.5.1` should be tagged as `1.5.3`.

**Comment by sconzof** [comment]
+1 please create a `1.5.3` release asap.

**Comment by nikolareljin** [comment]
+1 Can you please create the tag `1.5.3` for https://www.npmjs.com/package/dedent since the (non-existing) `1.5.2` in NPMjs breaks the installation of other dependent packages?

**Comment by JoshuaKGoldberg** [comment]
Sorry about that folks! I published `1.5.3` now that removes the added `engines` field altogether. Thanks for the quick bug reports!
